[package]
name = "ui-tests"
version = "0.1.0"
authors = ["Róbert Fuszenecker <robert.fuszenecker@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
selenium-rs = "0.1"

[dev-dependencies]